
--================ ANALYZING E-COMMERCE SALES DATA FOR MONTHS FEBRUARY THROUGH MAY======================

--=====================PART 1: ANSWERING BUSINESS QUESTIONS USING SQL QUERIES===========================

-- 1) MONTHLY SALES AND REFUND ANALYSIS
-- Determining monthly sales after subtracting cancelled and refunded orders.
WITH Monthly_Sales AS (
     SELECT DATENAME(MONTH, Order_Date) AS Month_Name, 
       ROUND(SUM(Total_Paid),2) AS Total_Amount, 
       SUM(refunded_amount) AS Total_Monthly_Refund
    FROM Orders
    WHERE Order_Date IS NOT NULL
    GROUP BY DATENAME(MONTH, Order_Date), MONTH(Order_Date)
)
SElECT Month_Name, Total_Amount, Total_Monthly_Refund,
       Total_Amount - Total_Monthly_Refund AS Revenue
FROM Monthly_Sales;

----------------------------------------------------------------------------------------------------------

-- 2) MONTHLY SALES PERFORMANCE
-- Calculating the total sales, total number of orders, and the average order value for each month.
SELECT DATENAME(MONTH, Order_date) AS Month, 
       ROUND(SUM(Total_Paid), 2) AS Revenue, 
       Count(o.Order_ID) as Total_Orders, 
       ROUND(SUM(Total_Paid) / NULLIF(COUNT(o.Order_ID), 0), 2) AS Average_Order_Value
FROM Orders o
WHERE DATENAME(MONTH, Order_date) IS NOT NULL
GROUP BY DATENAME(MONTH, Order_date), MONTH(Order_date)
ORDER BY MONTH(Order_date);

----------------------------------------------------------------------------------------------------------

-- 3) TOP 10 BEST-SELLING PRODUCTS
-- Identify the top 10 products based on quantity sold.
SELECT TOP 10 SKU, Item_Name, 
       SUM(Item_Quantity) AS Total_Quantity
FROM Products
GROUP BY SKU, Item_Name
ORDER BY Total_Quantity DESC;

----------------------------------------------------------------------------------------------------------

-- 4) REVENUE BY VENDOR
-- Calculating total revenue generated by each vendor and ranking them from highest to lowest.
SELECT vendor, 
       SUM(p.Item_Price * p.Item_Quantity) AS Total_Revenue
FROM Products p
GROUP BY vendor
ORDER BY Total_Revenue DESC;

----------------------------------------------------------------------------------------------------------

-- 5) SALES PERFORMANCE BY STATE
-- Determining which states generated the highest revenue.
SELECT Shipping_State, 
       ROUND(SUM(Total_Paid), 2) AS Sales_Per_State
FROM Orders o
JOIN CustomerInfo ci ON o.Order_ID = ci.Order_ID
WHERE Shipping_State IS NOT NULL
GROUP BY Shipping_State
ORDER BY Sales_Per_State DESC;

-- Verifying if the Total Revenue Per State is accurate by calculating a specific state's revenue
SELECT ROUND(SUM(Total_Paid), 2)
FROM  Orders o
JOIN CustomerInfo ci ON o.Order_ID = ci.Order_ID
WHERE Shipping_State = 'New York';

----------------------------------------------------------------------------------------------------------

-- 6) FULFILLMENT PERFORMANCE
-- Calculating the percentage of orders based on their financial status: Paid, Refunded, Voided etc...
SELECT Financial_Status, COUNT(*) AS Num_Orders, 
        CAST(
            ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 
            2) AS DECIMAL(5,2) 
         ) AS Percentage_of_Orders    
FROM Orders
WHERE Financial_Status IS NOT NULL
GROUP BY Financial_Status;

----------------------------------------------------------------------------------------------------------

-- 7) SHIPPING FEES ANALYSIS
-- Show the number of orders shipped and the Total Shipping paid based on the E-Commerce Platform 
-- and the Shipping Method used. 
SELECT Source, Shipping_Method,
       COUNT(O.Order_ID) AS Total_Orders,
       ROUND(SUM(Shipping_Price), 2) AS Total_Shipping_Fees
FROM Orders O
JOIN Products p ON o.Order_ID = p.Order_ID
WHERE Shipping_Method IS NOT NULL 
GROUP BY Source, Shipping_Method
ORDER BY Total_Shipping_Fees DESC;

----------------------------------------------------------------------------------------------------------

-- 8) AVERAGE SHIPPING COST ANALYSIS
-- Finding the average shipping cost for each shipping method.
SELECT Shipping_Method, 
       ROUND(AVG(Shipping_Price), 2) as AVG_Shipping_Cost
FROM Orders o
WHERE Shipping_Method IS NOT NULL
  AND Shipping_Price IS NOT NULL
GROUP BY Shipping_Method
ORDER BY AVG_Shipping_Cost DESC;

----------------------------------------------------------------------------------------------------------

-- 9) PRODUCT REVENUE ANALYSIS
-- Determine the revenue generated by each product
SELECT SKU, Item_Name, 
       CONCAT('$',SUM(Item_Quantity * Item_Price)) AS Total_Revenue
FROM Products p 
GROUP BY SKU, Item_Name
ORDER BY Total_Revenue DESC;

----------------------------------------------------------------------------------------------------------

-- 10) DISCOUNT ANALYSIS
-- Finding the Products receiving the largest discount amount
SELECT p.SKU,
       p.Item_Name,
       o.Discount_Amount
FROM Orders o
JOIN Products p ON o.Order_ID = p.Order_ID
WHERE o.Discount_Amount = (
    SELECT MAX(Discount_Amount)
    FROM Orders
    );

----------------------------------------------------------------------------------------------------------

-- 11) ANALYZING CUSTOMERS PAYING METHOD. 
-- Determining:Total revenue, the Number of orders placed
-- and the Average order value (AOV) based on the payment method used. 
SELECT Payment_Method, 
       COUNT(Order_ID) AS Total_Orders, 
       ROUND(SUM(Total_Paid),2) AS Total_Revenue, 
       ROUND(SUM(Total_Paid) / NULLIF(COUNT(Order_ID), 0), 2) AS AOV_Payment_Method
 -- OR ROUND(AVG(Total_Paid), 2) AS AOV_Payment_Method
FROM Orders 
WHERE Payment_Method IS NOT NULL
GROUP BY Payment_Method
ORDER BY Total_Orders DESC;

----------------------------------------------------------------------------------------------------------

-- 12) CUSTOMER MARKETING ANALYSIS 
-- COMPARE CUSTOMERS WHO ACCEPTED MARKETING VS THOSE WHO DID NOT.
-- Finding Average order value, Total revenue, Number of orders
SELECT Accepts_Marketing, 
       COUNT(o.Order_ID) AS Total_Orders, 
       ROUND(SUM(Total_Paid),2) AS Total_Revenue, 
       ROUND(AVG(Total_Paid), 2) AS AOV_Marketing_Status      
FROM CustomerInfo c
JOIN Orders o ON c.Order_ID = o.Order_ID
WHERE Accepts_Marketing IS NOT NULL
GROUP BY Accepts_Marketing
ORDER BY Total_Orders DESC;

----------------------------------------------------------------------------------------------------------
 
-- 13) VENDOR PERFORMANCE ANALYSIS
-- Ranking total items sold based on the vendor
SELECT Vendor, 
       CONCAT('$',SUM(Item_Quantity * Item_Price)) AS Total_Revenue, 
       ROW_NUMBER() OVER(ORDER BY SUM(Item_Quantity * Item_Price) DESC) Rank_Products
FROM Products
GROUP BY Vendor;

----------------------------------------------------------------------------------------------------------

-- 14) MONTHLY SOURCE PERFORMANCE ANALYSIS.
-- Finding the Monthy revenue generated by each e-commerce platform 
SELECT Source, 
       DATENAME(MONTH, Order_date) AS Month_Name, 
       ROUND(SUM(Total_Paid), 2) AS Total_Revenue
FROM Orders
WHERE Total_Paid is not null AND  DATENAME(MONTH, Order_date) IS NOT NULL 
GROUP BY Source, DATENAME(MONTH, Order_date), MONTH(Order_date)
ORDER BY MONTH(Order_date), Total_Revenue DESC;

----------------------------------------------------------------------------------------------------------

-- 15) FIND CUSTOMERS WHO SHIPPED ORDERS MORE THAN ONCE TO AN ADDRESS DIFFERENT FROM THEIR BILLING ADDRESS.
SELECT Billing_name, 
       COUNT(Order_ID) AS Num_orders
FROM CustomerInfo
WHERE Billing_Address != Shipping_Address
GROUP BY Billing_Name
HAVING COUNT(Order_ID) > 1
ORDER BY Num_orders DESC;

----------------------------------------------------------------------------------------------------------
-- 16) Determining the Monthly Sales amount minus the Total Orders that are cancelled/refunded. 
SELECT DATENAME(MONTH, Order_Date) AS Month_Name, 
       ROUND(SUM(Total_Paid),2) AS Total_Amount, 
       SUM(refunded_amount) AS Total_Monthly_Refund, 
       ROUND(SUM(Total_Paid) - SUM(refunded_amount), 2) AS Revenue
FROM Orders
WHERE Order_Date IS NOT NULL
GROUP BY DATENAME(MONTH, Order_Date), MONTH(Order_Date) 
ORDER BY MONTH(Order_Date);

-----------------------------------------------------------------------------------------------------------

-- 17) WEEKLY ORDERS & SALES ANALYSIS
-- Determine the total sales, the total numders of orders placed every week for each month.
SELECT DATENAME(MONTH, Order_Date) AS Month_Name,
       CONCAT('Week ', DATEPART(wk, Order_Date)) AS Week_Number,
       COUNT(Order_ID) AS Total_Weekly_Orders,
       ROUND(SUM(Total_Paid),2) AS Total_Weekly_Sales
FROM Orders
WHERE Order_Date IS NOT NULL
GROUP BY DATENAME(MONTH, Order_Date), MONTH(Order_Date), DATEPART(wk, Order_Date)
ORDER BY MONTH(Order_Date);

-----------------------------------------------------------------------------------------------------------

-- 18) LAST 30 DAY ANALYSIS
-- Find repeat customers who in the last 30 days had purchased more than once.
SELECT Billing_Name, 
       DATENAME(MONTH, Order_date) AS MONTH, 
       COUNT(o.Order_ID) AS Total_Orders
FROM CustomerInfo c
JOIN Orders o ON c.Order_ID = o.Order_ID
WHERE Order_date >= DATEADD(Day, - 30, Order_Date) 
      AND DATENAME(MONTH, Order_date) = 'April'
GROUP BY Billing_Name,  DATENAME(MONTH, Order_date)
HAVING COUNT(o.Order_ID) > 1;

-----------------------------------------------------------------------------------------------------------

-- 19) OVERNIGHT SHIPPING RATE ANALYSIS
SELECT Shipping_Method, 
       COALESCE(Shipping_State, 'Unknown State') AS Shipping_State,
       COUNT(o.Order_ID) AS Total_Orders
FROM CustomerInfo c
JOIN Orders o ON c.Order_ID = o.Order_ID
WHERE Shipping_Method LIKE 'Overnight%' 
      -- AND Shipping_State != 'New York'
GROUP BY Shipping_Method, Shipping_State
ORDER BY Total_Orders DESC;
